on: [push, pull_request]
name: Code coverage
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod download
      - name: Generate coverage report
        run: go test -v -timeout 60s -coverpkg=./... -coverprofile=coverage.tmp.txt -covermode=atomic ./...
      - name: Remove generated code from coverage report
        run: grep -v -E ".pb.go|_mock.go" coverage.tmp.txt > coverage.txt
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
